#!/usr/bin/env bash
set -euo pipefail

version="${1:?usage: ./scripts/adopt-goose.sh <last-applied-version>}"
if [[ ! "$version" =~ ^[0-9]+$ ]]; then
  echo "last-applied-version must be a non-negative integer" >&2
  exit 2
fi

# This is a one-time bridge for databases created with the legacy migration
# script. It is deliberately separate from migrate.sh so a new database is
# never marked as migrated without running the schema SQL.
docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U sol -d sol -v version="$version" <<'SQL'
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_tables
        WHERE schemaname = current_schema()
          AND tablename = 'goose_db_version'
    ) THEN
        RAISE EXCEPTION 'goose_db_version already exists; refusing to adopt again';
    END IF;
END $$;

CREATE TABLE goose_db_version (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp NOT NULL DEFAULT now()
);

INSERT INTO goose_db_version (version_id, is_applied)
SELECT version_id, true
FROM generate_series(0, :'version'::bigint) AS versions(version_id);
SQL

echo "Goose adopted at migration version $version. Run ./scripts/migrate.sh to apply newer migrations."
